# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  projectRoot: 'ECommerce'
  buildOutput: '$(projectRoot)/build'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
     echo "Listing ECommerce directory:"
     ls -la $(projectRoot)
     echo "Listing src directory:"
     ls -la $(projectRoot)/src
    displayName: 'Debug: list directory contents'

  - script: |
      npm install
      npm run build
    workingDirectory: '$(projectRoot)'
    displayName: 'Install dependencies and build React app'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(buildOutput)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive React build output'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifact'

